### ISSUE TITLE
Option to color nodes based on time spent in function rather than whole subtree

### ISSUE THREAD

**Issue by ArnaudBrousseau** [jrfonseca/gprof2dot#12]
This is a feature request to add a flag to color graph nodes based on time spent in each function, rather than coloring based on time spend in _the whole subtree_.

Concrete example (from https://github.com/jrfonseca/gprof2dot/blob/master/sample.png): `main` is colored red (since it's the call tree root), yet it's likely not a good place to look for optimizations. Same goes with small functions on top of expensive calls (`read_all_makefiles`). They should probably not be colored "hot" if they're fast. The expensive function call should!

I will look into implementing this soon if I have some spare time.

**Comment by jrfonseca** [comment]
> Concrete example : main is colored red (since it's the call tree root), yet it's likely not a good place to look for optimizations.

The way I read these graphs myself is starting from main, then follow the hottest children. That is, I rarely care for the "hot function", but rather the "hot code path". This is because knowing that a function is taking time is rarely enough -- one needs to know the context -- why the control flow goes into there.

For example, imagine a profile where the hottest function is memcpy -- it's probably the most optimized function of the C runtime already -- what one wants to know is which function is abusing of mempcy -- ie, which caller --, and if we color self times it's not obvious, but if we color total times it is.

That said, you're not the first to ask this ( https://code.google.com/p/jrfonseca/issues/detail?id=67 ) , and I can imagine cases where it can indeed be useful, so although I don't have motivation to write it myself, I'm happy to merge such patch.

It's not a trivial change -- you'll need to normalize the ratios by finding the hotest node and dividing all other ratios by it.
