### ISSUE TITLE
exception with gprof callgraph as written by libxslt.

### ISSUE THREAD

**Issue by ensonic** [jrfonseca/gprof2dot#4]
A long time ago a [wrote a patch for libxslt](https://bugzilla.gnome.org/show_bug.cgi?id=612186) to write xslt evaluation profiles in gprof compatible format. This makes gprof2dot an awesome tool to analyze xxslt slowness. Unfortunately I had to apply a little patch to gprof2dot - see below. This seems to be caused by special events: TIME and TOTAL_TIME. Do you have any insight here what goes wrong? I've uploaded a sample profile to: https://gist.github.com/ensonic/d78b65fc3d9067b97f82

```patch
￼diff --git a/gprof2dot.py b/gprof2dot.py
index 7a11b3a..9a6e7b9 100755
--- a/gprof2dot.py
+++ b/gprof2dot.py
@@ -491,7 +491,12 @@ class Profile(Object):
             return function[outevent]
     
     def _integrate_call(self, call, outevent, inevent):
-        assert outevent not in call
+        if outevent not in call:
+            # outevent 'Total time' not in call, inevent 'Time'
+            sys.stderr.write ("outevent '%s' not in call, inevent '%s'\n" % (outevent.name, inevent.name))
+            return 0
+        #assert outevent not in call
         assert call.ratio is not None
         callee = self.functions[call.callee_id]
         subtotal = call.ratio *self._integrate_function(callee, outevent, inevent)
```

**Comment by jrfonseca** [comment]
The problem is that your profile is not a DAG -- it has cycles.  Yet the gprof format establishes that cycles should be called out specially.

And your workaround is not really correct (as cycles will cause wrong results).  Instead the right workaround should be:

    diff --git a/gprof2dot.py b/gprof2dot.py
    index 7a11b3a..bd9026b 100755
    --- a/gprof2dot.py
    +++ b/gprof2dot.py
    @@ -1234,6 +1234,7 @@ class GprofParser(Parser):
     
             # Compute derived events
             profile.validate()
    +        profile.find_cycles()
             profile.ratio(TIME_RATIO, TIME)
             profile.call_ratios(CALLS)
             profile.integrate(TOTAL_TIME, TIME)

That said, `gprof` format is old and cumbersome. Rather than trying to mimic gprof I'd recommend outputing in the custom and simple https://github.com/jrfonseca/gprof2dot/tree/master/tests/json format.  It's not thoroughly documented but it's quite easy: you have an array of functions (nodes), a bunch of call stacks (edges), each with a cost.

**Comment by ensonic** [comment]
Thanks, with "profile.find_cycles()" the graphs are also correct. I'll take a look at the json output as an alternative or see if I can fix the current output (as documented in https://sourceware.org/binutils/docs/gprof/Cycles.html)
