### ISSUE TITLE
Visualization results are abnormal

### ISSUE THREAD

**Issue by eecho-ohcee** [jrfonseca/gprof2dot#64]
Hello,
The picture I got after using the Gprof2Dot visualization tool did not show the details of the function call between the python program modules. But this information is what I need, what should I do. The png image I got is provided in the attachment. The command line parameters are as follows.
Looking forward to your answer.
# python -m cProfile -o output.pstats spades.py -t 28 -m 1024 --meta -k 21,33,55,77 -1 output_forward_paired.fq.gz -2 output_reverse_paired.fq.gz -o ./spa_out
# python gprof2dot.py -f pstats output.pstats | dot -x -Tpng -o output.png
![output](https://user-images.githubusercontent.com/73236687/105574216-0aa91080-5d9e-11eb-821b-4baa5dd91760.png)

**Comment by eecho-ohcee** [comment]
Append:
I used another simple python program to test, and the visualized pictures obtained were normal. I think the previous python program was too complicated to show all the calling relationships. Help: Is it possible to visualize only part of the modules in the python program, and how to achieve it?

**Comment by jrfonseca** [comment]
The graph you showed tells that most of the time on your Python program (99.85% to be precisey) was spent reading on I/O, reading lines from a file.   All the calling functions were slow because of that.

This means if you want to to speed up your program you need to make file reads faster.  For example, using faster storage (ie, store files on faster SSDs or even memory), or use memory mapped files, etc.

> Is it possible to visualize only part of the modules in the python program, and how to achieve it?

There are options to visualize parts of the graph, see `gprof2dot.py --help`, in particular the `--root`, `--leaf` and `--path` options.

**Comment by eecho-ohcee** [comment]
Thanks a lot!
