### ISSUE TITLE
gprof get empty gmon.out?

### ISSUE THREAD

**Issue by nickhuangxinyu** [jrfonseca/gprof2dot#69]
i run my code as :

./my_bin myconfig > a

i got a gmon.out, but its size is only 322byte, and contains no info. the code is time costly, cost 20s to run.

I am desperate about this, because i do as most blog, step by step.

but cant get my gmon.out well, can you help on this?

compiler: i use gcc, cmake, -O2 -std=c++11 -g -pg

**Comment by jrfonseca** [comment]
It's impossible for me to know what's going on without source code.

If you're using CMake, make sure you pass `-g -pg` options always: when compiling and linking files.

Instead of gprof, try Linux perf, which shouldn't require any changes to your build, hence might be easier to use:
- https://perf.wiki.kernel.org/index.php/Main_Page
- https://github.com/jrfonseca/gprof2dot#linux-perf

If you're desperate, another solution is to run you code inside the debugger, break, and look at the stack back trace.  You can do that many times during the 20s to get a feel where time is being spent.

Or you can simply log and/or add timings.

I hope this helps.
