### ISSUE TITLE
valgrind: A lot of information is lost, graph has few disconnected components

### ISSUE THREAD

**Issue by Akuli** [jrfonseca/gprof2dot#76]
asdf.c:

```c
#include <stdio.h>
#include <SDL2/SDL.h>

void a(void) {
	long long sum = 0;
	for (long long i = 0; i <= 100000000LL; i++)
		sum += i;
	printf("%lld\n", sum);
}
void b(void) { a(); }
void c(void) { b(); }
int main(void) { SDL_CreateWindow("a", 5, 5, 100, 100, 0); c(); return 0; }
```

commands:

```
gcc asdf.c -lSDL2
valgrind --tool=callgrind --callgrind-out-file=callgrind.out ./a.out
gprof2dot callgrind.out --format=callgrind --output=foo.dot
dot -Tpng foo.dot -o foo.png
```

resulting `foo.png`:

![foo](https://user-images.githubusercontent.com/18505570/145601817-eeb7b74b-0dc5-41fe-ba6b-452960344ddf.png)

I believe the problem is in gprof2dot, because `kcachegrind callgrind.out` correctly shows that most of the time is spent in `a()`:

![k](https://user-images.githubusercontent.com/18505570/145601420-fdc8ee64-a794-4ac2-846d-1e93f178147a.png)

Content of `callgrind.out` (71191 lines): https://termbin.com/e2k8

If I comment out the call to `SDL_CreateWindow()`, valgrind's `brk segment overflow in thread #1` warning disappears, and I also get much better results:

![foo](https://user-images.githubusercontent.com/18505570/145601539-269c0c39-41c6-41be-81c1-3ea6994bd1d8.png)

**Comment by jrfonseca** [comment]
Sorry for the silence.  I don't know how I missed this issue's notification.  I've just noticed now as I'm checking over all my projects.

As documented [here](https://github.com/jrfonseca/gprof2dot#which-options-should-i-pass-to-gcc-when-compiling-for-profiling) there are several flags one should pass to gcc, particularly `-g` and `-fno-omit-frame-pointer`.

But I tried without those settings, and I got a sensible graph:

![foo](https://user-images.githubusercontent.com/140183/233593138-5730d2f7-13e7-4106-aa6f-793e4b551eec.png)

I even tried with `-s` and `-fomit-frame-pointer` and still the graph looked sensible.

It's certainly odd the `a()` function didn't show up at all anywhere, and that kcachegrind handled it fine.

There's nothing here I can do.  If the issue persists, attach `callgrind.out`, as https://termbin.com/e2k8 is dead.

**Comment by Akuli** [comment]
Thanks for responding! I tried with `gcc -g -fno-omit-frame-pointer asdf.c -lSDL2`, and got a bad graph again.

![foo](https://user-images.githubusercontent.com/18505570/233621769-7ef819be-0a7f-4232-ba65-384fccb7c82a.png)

I uploaded `callgrind.out` (70373 lines this time) to github gist: https://gist.github.com/Akuli/ca1352aa029e88df542d212f95cdfd15

**Comment by Akuli** [comment]
Here is a zip file of `callgrind.out` in case you cannot download the gist: 
[callgrind-out.zip](https://github.com/jrfonseca/gprof2dot/files/11295195/callgrind-out.zip)

**Comment by jrfonseca** [comment]
Thanks.  The `a()` is being parsed, but it's being pruned.

The issue down to `_dl_runtime_resolve_fxsave` function: it seems that most calls to external SO symbols (including from `a()` to `printf()`) gets redirected to this trampoline function, and the call graph is essentially a big ball of spagetthi, as `_dl_runtime_resolve_fxsave` is both the caller and callee of pretty much every single function... 

In other words, a big chunk of the graph is a cycle (instead of being a nice looking DAG).  And `gprof2dot.py` can't really propagate cost across the the functions inside a cycle (though perhaps it should do better than it does now, as pruning the whole cycle seems pretty awful.)


The ideal would be to to somehow ignore `_dl_runtime_resolve_fxsave`, but it's not possible because Callgrind format doesn't preserve full call stack info: it states that `a -> _dl_runtime_resolve_fxsave`, and it states that `_dl_runtime_resolve_fxsave -> printf` among many others, but it doesn't say 


I can try to handle this slightly better, but these are all hacks:  garbage in, garbage out.


Honestly I think you're better off using something like linux perf instead of callgrind.

**Comment by jrfonseca** [comment]
Also relevant:
- https://bugzilla.redhat.com/show_bug.cgi?id=1784541
- https://bugs.kde.org/show_bug.cgi?id=415293#c6
- https://sourceware.org/git/?p=valgrind.git;a=commitdiff;h=86277041a296d3ca34d938b347c246ff4485c3a0

So it seems this has been fixed in valgrind.

Which version of valgrind are you using?  This is mine:

```bash
$ valgrind --version
valgrind-3.18.1
```

**Comment by Akuli** [comment]
Thanks for figuring this out! I am using valgrind 3.16.1, released before the commit that fixes this. I will compile valgrind from source or try linux `perf` next time I need to profile a project that uses SDL2.
