### ISSUE TITLE
Not working with graphviz 2.50.0?

### ISSUE THREAD

**Issue by Bexa2** [jrfonseca/gprof2dot#79]
I get the error `Error: <stdin>: syntax error in line 1 near 'digraph'` when running `gprof2dot -f pstats output.pstats | dot -Tpng -o output.png`

**Comment by jrfonseca** [comment]
Sorry, @Bexa2 , I somehow missed this issue until now.

I just ran the test suite with graphviz 2.50.0 and all went fine.

If the issue is still there, please provide me `output.pstats` so I can try to reproduce this.  If it includes sensitive information, you can email it to `jose dot r dot fonseca at gmail dot com`
