### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by ffernandoalves** [jrfonseca/gprof2dot#88]
This error appears when I run: ` python3.11 -m gprof2dot -o main_gprof2dot.dot main_gprof.txt` on Windows 11

I generate the prof as follows::
```
g++ -g -pg main.cpp -o main.exe
.\main.exe
gprof .\main.exe .\gmon.out > main_gprof.txt
````

However, it works when I changed the reading encoding to `"utf-16le"`, in gprof2dot.py:
```python
...
if Format.stdinInput:
    if not args:
        fp = sys.stdin
    elif PYTHON_3:
        # fp = open(args[0], 'rt', encoding='UTF-8')
        fp = open(args[0], 'rt', encoding="utf-16le")
    else:
        fp = open(args[0], 'rt')
    parser = Format(fp)
...
```

g++ version:
```
g++.exe (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.1.0
```

**Comment by jrfonseca** [comment]
I'm surprised gprof would output non-ASCII characters to start with.

Perhaps you were using PowerShell instead of Command Prompt?  According to https://superuser.com/questions/961697/redirecting-output-in-powershell-produces-utf-16-encoded-text it seems PowerShell uses utf-16 to text redirection.

Ideally gprof2dot.py would auto detect the encoding.

If there's nothing confidential, could you please attach that `main_gprof.txt`?
